### ISSUE TITLE
For Android

### ISSUE THREAD

**Issue by AdityaMH** [deltaclock/emu-paradise-download#7]
Can you create this for android?

**Comment by deltaclock** [comment]
You can already run this script on android by using [termux](https://play.google.com/store/apps/details?id=com.termux&hl=en) and following the [linux](https://github.com/deltaclock/emu-paradise-download#linux-and-macos) instructions.

**Comment by AdityaMH** [comment]
how to run script for termux?

**Comment by deltaclock** [comment]
You firstly need to install python, git, pip and after that's done follow the linux instructions like I said above.

**Comment by AdityaMH** [comment]
I don't know why, but program say: "Error: Unable to create directory '/storage/emulated/0/emuDl.py'" even i allow termux to read storage.
